### ISSUE TITLE
last version of TI Os

### ISSUE THREAD

**Issue by ghost** [TI-Planet/eval_expr#2]
In the last version I get the following:
>>import ti_st
>>print(help(ti_st))

object <module 'ti_st'> is of type module
  __name__ -- ti_st
  readST -- <function>
  readSTNum -- <function>
  readSTLst -- <function>
  writeST -- <function>
  evalFunc -- <function>
  writeSTLst -- <function>
  getKey -- <function>
  wait -- <function>
  get_platform -- <function>
  disp_clr -- <function>
  getmouse -- <function>
  get_time_ms -- <function>

So there are also readSTNum, readSTLst and  writeSTLst. I do not know so much of Python and the TI-NSpire to do anything with that functions. But maybe you? Also I do not know how to list the parameters of the undocumented functions. Is there a way?
By the way: Great work!

**Comment by adriweb** [comment]
Right, this is basically what's documented here, I'm not sure if there's any surprise: https://education.ti.com/html/webhelp/EG_TINspire/EN/Subsystems/EG_Python/Content/m_menumap/mm_tisystem.HTML

Although I'll need to check if readSTNum can be used in some cases (but generally we always prefer the generic version, readST)

**Comment by adriweb** [comment]
I'm not currently working on this anymore (especially because of the weird issue in #1), but PRs are welcome anyway.
