### ISSUE TITLE
does not work any more

### ISSUE THREAD

**Issue by ghost** [TI-Planet/eval_expr#3]
I tested the functions today, but they do not work anymore. ;-(

Checked it with the original TI Student Software and two calculators, a CX II-T and a CX II-T CAS. 
I used the simple expression 
eval_expr("sqrt(90)",True) - that one from your example. (Tested False or no second param also)
On the CAS I get: line 38, in eval_expr
TypeError: Invalid number format
That is the line: res = readST("tmppy_")  # retrieve stored value

On the non-CAS I get: py", line 37, in eval_expr
TypeError: Variable storage failed
And thats the line:   writeST("tmppy_", 'strsub(string('+str(expr)+'),"/","$%$")')  # eval and store

Calculator-Software: 5.3.0.564 on both calculators.

Any chance to fix the problem, or has evil TI blocked that method?

**Comment by adriweb** [comment]
This isn't actually new, see #1.
