### ISSUE TITLE
Error: Invalid number format

### ISSUE THREAD

**Issue by smeston** [TI-Planet/eval_expr#4]
```py
from eval_expr import*
from math import *
from eval_expr import eval_expr
eval_expr("sqrt(90)", True)
```
Gives error: 
```
"C:\Users\sanje\AppData\Roaming\Texas Instruments\TI-Nspire CX CAS Premium Teacher Software\PyExtract\eval_expr.py", line 38, in  eval_expr
TypeError: Invalid number format
```

**Comment by adriweb** [comment]
Sorry I can't reproduce the problem, it works fine for me (on both the TI-Nspire CX CAS Premium Teacher Software 5.4 and 6.0):

![CleanShot 2024-03-04 at 11 14 27@2x](https://github.com/TI-Planet/eval_expr/assets/660896/6694c15c-c1ca-4ee4-af8c-38636debd0d7)

**Comment by adriweb** [comment]
Ah yeah so it's probably the same as #1 where it might not work if imported from another document... It might be a TI bug I'm not sure.
You could always copy/paste the `eval_expr` function into your own code as a workaround,
