### ISSUE TITLE
Tried on another Laptop

### ISSUE THREAD

**Issue by smeston** [TI-Planet/eval_expr#5]
Still the same issue
Tried on another laptop. I am using 6.0.3.374 
Can you kindly send me your file, so I can compare.
![image](https://github.com/TI-Planet/eval_expr/assets/52845804/27a99eb7-b79a-4599-a792-1ef9652d49c8)

**Comment by smeston** [comment]
![image](https://github.com/TI-Planet/eval_expr/assets/52845804/04476e91-34d1-47c0-b685-751fc7fc8a2a)

**Comment by adriweb** [comment]
(continuing in #4)
